Bug/cpuvalidmax
netuitive-community-packages/netuitive-packages-aws-ecs pull request #13
Opened 2019-05-17 21:28 UTC by codytipton

CPUutil will not be normalized at the service level. So we shouldn't set a valid max for CPU util here. Otherwise rollup data will have blanks.

2019-05-18 11:34 UTC, TheConnMan approved these changes

2019-05-18 11:35 UTC, TheConnMan requested changes

2019-05-18 11:35 UTC, TheConnMan commented on analyticConfigurations/metric_meta-aws.ecs.service.json
> +        "match": "^aws\\.ecs\\.memory.*",
I think memory will have this issue as well. Some of our services run over 100%.

2019-05-20 13:23 UTC, yadima approved these changes

2019-05-20 13:46 UTC, rclagett approved these changes

2019-05-20 15:22 UTC, TheConnMan approved these changes

2019-05-20 15:23 UTC, merged